# Creating numpy array

In [1]:
import numpy as np
a = np.array([0,1,2,3])
print(a)

[0 1 2 3]


In [2]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


# Lists

In [3]:
L= range(1000)
%timeit [i**2 for i in L]

245 µs ± 392 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
a=np.arange(1000)
%timeit a**2

859 ns ± 0.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Manual Construction of Arrays

In [5]:
# 1-D Array

a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

# Print Dimensions

In [6]:
a.ndim

1

# Shape of Numpy Array

In [7]:
a.shape

(4,)

In [8]:
#2-D, 3-D ...

b= np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
b.ndim

2

In [10]:
b.shape

(2, 3)

In [11]:
len(b) # returns the size of first dimension

2

In [16]:
c= np.array([[[0,1],[2,3]],[[4,5],[6,7]]],dtype=object)
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=object)

In [17]:
c.ndim

3

In [18]:
c.shape

(2, 2, 2)

# Functions for creating Arrays

1. Using arange function

In [19]:
a=np.arange(10) #0... n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
b=np.arange(1,10,2) # start, end, step
b

array([1, 3, 5, 7, 9])

2. Using linspace

In [22]:
a=np.linspace(0,1,6) # start, end, number of decimal points
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

3. Common arrays

In [23]:
#creates float values
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
#Identity Matrix

c=np.eye(3) # returns a 2-D array with ones on the diagonal and zeros elsewhere
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
d=np.eye(3,2)
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

4. Using diag function

In [27]:
a=np.diag([1,2,3,4]) # construct a diagonal array
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [28]:
np.diag(a) # Extract diagonal elements

array([1, 2, 3, 4])

5.Using random function

In [29]:
a=np.random.rand(4) # populate an array of given shape with random values
a

array([0.41015976, 0.4414509 , 0.94930346, 0.26297887])

In [30]:
a=np.random.randn(4) # Return a sample from the standard normalisation
a

array([ 0.23302992, -1.82443523,  0.25907797,  0.56350465])

In [31]:
a.dtype # type of numpy array

dtype('float64')

In [32]:
a = np.arange(10,dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [33]:
d=np.array([1+2j,2+4j]) #complex datatype
d.dtype

dtype('complex128')

In [34]:
b=np.array([True,False,True,False]) # Boolean datatype
b.dtype

dtype('bool')

In [35]:
s = np.array(['Hai','Hello','How'])
s.dtype

dtype('<U5')

# Indexing 

In [39]:
a=np.arange(10)
print(a[5])

5


In [40]:
a=np.diag([1,2,3]) 
print(a[2,2])

3


In [41]:
a[2,1] = 5 # assigning a value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

# Slicing

In [42]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
b[1:8:2] # start, end, step

array([1, 3, 5, 7])

In [44]:
#combine assignment and slicing
a=np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [45]:
b=np.arange(5)
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

# Copies and Views 

In [46]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
b=a[::2]
b

array([0, 2, 4, 6, 8])

In [48]:
np.shares_memory(a,b)

True

In [49]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [50]:
a # a is modified as b is modified since they share memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [51]:
a=np.arange(10)
c=a[::2].copy() # force a copy
c

array([0, 2, 4, 6, 8])

In [52]:
np.shares_memory(a,c)

False

In [53]:
c[0]=10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#  Fancy Indexing

Masks create copies and not views

In [54]:
a=np.random.randint(0,20,15)
a

array([ 0, 13, 13,  9, 14,  7,  5,  7,  8, 15, 17,  4, 18,  5, 13])

In [55]:
mask = (a%2==0)

In [56]:
extract_from_a = a[mask]
extract_from_a

array([ 0, 14,  8,  4, 18])

In [57]:
a[mask] = -1
a

array([-1, 13, 13,  9, -1,  7,  5,  7, -1, 15, 17, -1, -1,  5, 13])

# Indexing with array of integers

In [58]:
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [59]:
#Indexing can be done with an array of integers
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [60]:
# Assign new values
a[[9,7]]= -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])